spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    test-connection: true
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  forward-headers-strategy: framework
  shutdown: graceful

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    com.roletadefilmes: INFO
